= Lab 1: VM Startup Troubleshooting

== Overview & Objectives

This lab focuses on diagnosing and resolving Virtual Machine startup issues in OpenShift Virtualization.

* Understand the OpenShift Virtualization VM startup workflow and object lifecycle.
* Inspect key Kubernetes/OpenShift objects including VirtualMachine (VM), VirtualMachineInstance (VMI), virt-launcher pods, PersistentVolumeClaims (PVC), and DataVolumes (DV).

== Tasks

=== Task 1: Troubleshooting Failure Scenario A

==== Problem Scenario

A Virtual Machine is configured with a container disk image in namespace {{ bootstrap_tenant_username }}-troubleshoot-01. When attempting to start the VM, the startup process fails.

==== Reference Documentation & Setup

* Consult the documentation on link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.22/html/virtualization/creating-virtual-machines#virt-creating-vm-import-cli_virt-creating-vms-from-container-disks[Creating VMs from Container Disks].
* The VM is configured to use container disks.

==== Diagnostic Commands

Run the following commands in sequence to inspect the VM startup workflow:

[source,sh]
----
oc get vm
oc get vmi
oc describe vmi <vm-name>
oc get pods -l kubevirt.io/created-by=<vmi-uid>
oc describe pod <virt-launcher-pod>
oc get pvc
oc get dv
oc get events
----

=== Task 2: Troubleshooting Failure Scenario B

==== Problem Scenario

A Virtual Machine fails to start as expected. Investigate the issue to determine the root cause and restore the VM to a running state.

==== Diagnostic Commands

Execute the following commands to check the state of the relevant objects:

[source,sh]
----
oc get vm
oc get vmi
oc describe vmi <vm-name>
oc get pods -l kubevirt.io/created-by=<vmi-uid>
oc describe pod <virt-launcher-pod>
oc get pvc
oc get dv
oc get events
----
